project:
  type: website
  output-dir: docs
  preview: 
    port: 4040



website:
  title: "Tutoriels LF2L"
  site-url: ""
  repo-url: "https://github.com/fabbiocrux/LF2L-Tutorial" 
  search:
    type: overlay  
  page-footer:
    left: |
      Développé par :
      [![](images/LF2L-Vertical.png){fig-alt="LF2L" width=65px}](https://lf2l.fr/)
    center:
      - text: "Lorraine Fab Living Lab"
  navbar:
    background: light
    logo: images/LF2L-Vertical.png
    logo-alt: "Lorraine Fab Living Lab"
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        href: https://github.com/LF2L/LF2L-Tutorial
        text: GitHub
  sidebar:
      style: "docked"
      search: true
      
      contents:
        - section: "Impression 3D"
          contents:                
            - printing/theorie.qmd
            - printing/tutoriels.qmd
        - section: "Découpe laser"
          contents:                        
            - laser-cut/theorie.qmd
            - laser-cut/tutoriels.qmd
        - section: "Electronique & controle"    
          contents:                
            - electronics/theorie.qmd
            - electronics/tutoriels.qmd

  page-navigation: true
  back-to-top-navigation: true



format:
  html:
    theme: cosmo
    css: assets/LF2L.scss
    toc: true
    lang: fr

license: CC BY-SA

execute: 
  cache: true
  freeze: true  # re-render only when source changes